package Aspose.Tasks;

public enum AsnKey {
  Guid(0L),
  Uid(1L),
  Task(2L),
  Resource(3L),
  PercentWorkComplete(4L),
  ActualCost(5L),
  ActualFinish(6L),
  ActualOvertimeCost(7L),
  ActualStart(8L),
  ActualWork(9L),
  ActualOvertimeWork(10L),
  ACWP(11L),
  Confirmed(12L),
  Cost(13L),
  CostRateTableType(14L),
  CostVariance(15L),
  CV(16L),
  Delay(17L),
  Finish(18L),
  FinishVariance(19L),
  Hyperlink(20L),
  HyperlinkAddress(21L),
  HyperlinkSubAddress(22L),
  WorkVariance(23L),
  HasFixedRateUnits(24L),
  FixedMaterial(25L),
  LevelingDelay(26L),
  LevelingDelayFormat(27L),
  LinkedFields(28L),
  Milestone(29L),
  Notes(30L),
  Overallocated(31L),
  OvertimeCost(32L),
  OvertimeWork(33L),
  PeakUnits(34L),
  RegularWork(35L),
  RemainingCost(36L),
  RemainingOvertimeCost(37L),
  RemainingOvertimeWork(38L),
  RemainingWork(39L),
  ResponsePending(40L),
  Start(41L),
  Stop(42L),
  Resume(43L),
  StartVariance(44L),
  Summary(45L),
  SV(46L),
  Units(47L),
  UpdateNeeded(48L),
  VAC(49L),
  Work(50L),
  WorkContour(51L),
  BCWS(52L),
  BCWP(53L),
  BookingType(54L),
  ActualWorkProtected(55L),
  ActualOvertimeWorkProtected(56L),
  Created(57L),
  AssignmentOwner(58L),
  AssignmentOwnerGuid(59L),
  BudgetWork(60L),
  BudgetCost(61L),
  RateScale(62L),
  TaskUid(63L),
  ResourceUid(64L),
  ;
  private long numVal;

  AsnKey(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
