package Aspose.Tasks;

public enum PrjKey {
  ShowProjectSummaryTask(0L),
  SaveVersion(1L),
  Uid(2L),
  Title(3L),
  Subject(4L),
  Category(5L),
  Company(6L),
  Manager(7L),
  Author(8L),
  CreationDate(9L),
  Revision(10L),
  LastSaved(11L),
  ScheduleFromStart(12L),
  StartDate(13L),
  FinishDate(14L),
  FyStartDate(15L),
  CriticalSlackLimit(16L),
  CurrencyDigits(17L),
  CurrencySybmol(18L),
  CurrencyCode(19L),
  CurrencySymbolPosition(20L),
  Calendar(21L),
  DateFormat(22L),
  DefaultStartTime(23L),
  DefaultFinishTime(24L),
  MinutesPerDay(25L),
  MinutesPerWeek(26L),
  DaysPerMonth(27L),
  DefaultTaskType(28L),
  DefaultFixedCostAccrual(29L),
  DefaultStandardRate(30L),
  DefaultOvertimeRate(31L),
  DurationFormat(32L),
  WorkFormat(33L),
  AreEditableActualCosts(34L),
  HonorConstraints(35L),
  EarnedValueMethod(36L),
  InsertedProjectsLikeSummary(37L),
  MultipleCriticalPaths(38L),
  NewTasksEffortDriven(39L),
  NewTasksEstimated(40L),
  SplitsInProgressTasks(41L),
  SpreadActualCosts(42L),
  SpreadPercentComplete(43L),
  TaskUpdatesResource(44L),
  FiscalYearStart(45L),
  WeekStartDay(46L),
  MoveCompletedEndsBack(47L),
  MoveRemainingStartsBack(48L),
  MoveRemainingStartsForward(49L),
  MoveCompletedEndsForward(50L),
  BaselineForEarnedValue(51L),
  AutoAddNewResourcesAndTasks(52L),
  StatusDate(53L),
  CurrentDate(54L),
  MicrosoftProjectServerURL(55L),
  Autolink(56L),
  NewTaskStartDate(57L),
  DefaultTaskEVMethod(58L),
  ExtendedCreationDate(59L),
  ActualsInSync(60L),
  ProjectExternallyEdited(61L),
  RemoveFileProperties(62L),
  AdminProject(63L),
  Name(64L),
  TimescaleStart(65L),
  TimescaleFinish(66L),
  Comments(67L),
  Keywords(68L),
  Template(69L),
  LastAuthor(70L),
  LastPrinted(71L),
  HyperlinkBase(72L),
  NewTasksAreManual(73L),
  UpdateManuallyScheduledTasksWhenEditingLinks(74L),
  KeepTaskOnNearestWorkingTimeWhenMadeAutoScheduled(75L),
  DefaultCalendarGuid(76L),
  DefaultCalendarUid(77L),
  ;
  private long numVal;

  PrjKey(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
