package Aspose.Tasks;

public enum ResourceUsageViewField {
  Work(0L),
  OvertimeWork(1L),
  ActualWork(2L),
  ActualOvertimeWork(3L),
  CumulativeWork(4L),
  BaselineWork(5L),
  Overallocation(6L),
  PercentAllocation(7L),
  PeakUnits(8L),
  Cost(9L),
  ActualCost(10L),
  BaselineCost(11L),
  CumulativeCost(12L),
  BCWS(13L),
  BCWP(14L),
  ACWP(15L),
  SV(16L),
  CV(17L),
  RegularWork(18L),
  RemainingAvailability(19L),
  UnitAvailability(20L),
  WorkAvailablility(21L),
  Baseline1Work(22L),
  Baseline1Cost(23L),
  Baseline2Work(24L),
  Baseline2Cost(25L),
  Baseline3Work(26L),
  Baseline3Cost(27L),
  Baseline4Work(28L),
  Baseline4Cost(29L),
  Baseline5Work(30L),
  Baseline5Cost(31L),
  Baseline6Work(32L),
  Baseline6Cost(33L),
  Baseline7Work(34L),
  Baseline7Cost(35L),
  Baseline8Work(36L),
  Baseline8Cost(37L),
  Baseline9Work(38L),
  Baseline9Cost(39L),
  Baseline10Work(40L),
  Baseline10Cost(41L),
  BudgetWork(42L),
  BudgetCost(43L),
  BaselineBudgetWork(44L),
  BaselineBudgetCost(45L),
  Baseline1BudgetWork(46L),
  Baseline1BudgetCost(47L),
  Baseline2BudgetWork(48L),
  Baseline2BudgetCost(49L),
  Baseline3BudgetWork(50L),
  Baseline3BudgetCost(51L),
  Baseline4BudgetWork(52L),
  Baseline4BudgetCost(53L),
  Baseline5BudgetWork(54L),
  Baseline5BudgetCost(55L),
  Baseline6BudgetWork(56L),
  Baseline6BudgetCost(57L),
  Baseline7BudgetWork(58L),
  Baseline7BudgetCost(59L),
  Baseline8BudgetWork(60L),
  Baseline8BudgetCost(61L),
  Baseline9BudgetWork(62L),
  Baseline9BudgetCost(63L),
  Baseline10BudgetWork(64L),
  Baseline10BudgetCost(65L),
  AllResourceRows(66L),
  AllAssignmentRows(67L),
  Undefined(-1L),
  ;
  private long numVal;

  ResourceUsageViewField(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
