package Aspose.Tasks;

public enum RscKey {
  Name(0L),
  AccrueAt(1L),
  ActualCost(2L),
  ActualOvertimeCost(3L),
  ActualOvertimeWork(4L),
  ActualOvertimeWorkProtected(5L),
  ActualWork(6L),
  ActualWorkProtected(7L),
  ACWP(8L),
  AssignmentOwner(9L),
  AssignmentOwnerGuid(10L),
  AssignmentUnits(11L),
  AvailableFrom(12L),
  AvailableTo(13L),
  ActiveDirectoryGuid(14L),
  BaseCalendar(15L),
  BCWP(16L),
  BCWS(17L),
  BookingType(18L),
  BudgetWork(19L),
  BudgetCost(20L),
  Calendar(21L),
  CanLevel(22L),
  Code(23L),
  Confirmed(24L),
  Cost(25L),
  CostCenter(26L),
  CostPerUse(27L),
  CostRateTable(28L),
  CostVariance(29L),
  Created(30L),
  CV(31L),
  SV(32L),
  EMailAddress(33L),
  IsBudget(34L),
  IsGeneric(35L),
  IsEnterprise(36L),
  IsCostResource(37L),
  Inactive(38L),
  Finish(39L),
  Group(40L),
  GroupbySummary(41L),
  Guid(42L),
  Hyperlink(43L),
  HyperlinkAddress(44L),
  HyperlinkHref(45L),
  HyperlinkSubAddress(46L),
  Id(47L),
  Initials(48L),
  IsAssignment(49L),
  IsNull(50L),
  IsTeamAssignmentPool(51L),
  LevelingDelay(52L),
  LinkedFields(53L),
  MaterialLabel(54L),
  MaxUnits(55L),
  Notes(56L),
  NotesRTF(57L),
  NotesText(58L),
  Overallocated(59L),
  OvertimeCost(60L),
  OvertimeRate(61L),
  OvertimeRateFormat(62L),
  OvertimeWork(63L),
  PeakUnits(64L),
  PercentWorkComplete(65L),
  Phonetics(66L),
  Project(67L),
  RegularWork(68L),
  RemainingCost(69L),
  RemainingOvertimeCost(70L),
  RemainingOvertimeWork(71L),
  RemainingWork(72L),
  ResponsePending(73L),
  StandardRate(74L),
  StandardRateFormat(75L),
  Start(76L),
  Type(77L),
  Uid(78L),
  VAC(79L),
  WBS(80L),
  WindowsUserAccount(81L),
  Work(82L),
  WorkContour(83L),
  Workgroup(84L),
  WorkVariance(85L),
  ;
  private long numVal;

  RscKey(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
