package Aspose.Tasks;

public enum TimephasedDataType {
  AssignmentRemainingWork(1L),
  AssignmentActualWork(2L),
  AssignmentActualOvertimeWork(3L),
  AssignmentBaselineWork(4L),
  AssignmentBaselineCost(5L),
  AssignmentActualCost(6L),
  ResourceBaselineWork(7L),
  ResourceBaselineCost(8L),
  TaskBaselineWork(9L),
  TaskBaselineCost(10L),
  TaskPercentComplete(11L),
  AssignmentBaseline1Work(16L),
  AssignmentBaseline1Cost(17L),
  TaskBaseline1Work(18L),
  TaskBaseline1Cost(19L),
  ResourceBaseline1Work(20L),
  ResourceBaseline1Cost(21L),
  AssignmentBaseline2Work(22L),
  AssignmentBaseline2Cost(23L),
  TaskBaseline2Work(24L),
  TaskBaseline2Cost(25L),
  ResourceBaseline2Work(26L),
  ResourceBaseline2Cost(27L),
  AssignmentBaseline3Work(28L),
  AssignmentBaseline3Cost(29L),
  TaskBaseline3Work(30L),
  TaskBaseline3Cost(31L),
  ResourceBaseline3Work(32L),
  ResourceBaseline3Cost(33L),
  AssignmentBaseline4Work(34L),
  AssignmentBaseline4Cost(35L),
  TaskBaseline4Work(36L),
  TaskBaseline4Cost(37L),
  ResourceBaseline4Work(38L),
  ResourceBaseline4Cost(39L),
  AssignmentBaseline5Work(40L),
  AssignmentBaseline5Cost(41L),
  TaskBaseline5Work(42L),
  TaskBaseline5Cost(43L),
  ResourceBaseline5Work(44L),
  ResourceBaseline5Cost(45L),
  AssignmentBaseline6Work(46L),
  AssignmentBaseline6Cost(47L),
  TaskBaseline6Work(48L),
  TaskBaseline6Cost(49L),
  ResourceBaseline6Work(50L),
  ResourceBaseline6Cost(51L),
  AssignmentBaseline7Work(52L),
  AssignmentBaseline7Cost(53L),
  TaskBaseline7Work(54L),
  TaskBaseline7Cost(55L),
  ResourceBaseline7Work(56L),
  ResourceBaseline7Cost(57L),
  AssignmentBaseline8Work(58L),
  AssignmentBaseline8Cost(59L),
  TaskBaseline8Work(60L),
  TaskBaseline8Cost(61L),
  ResourceBaseline8Work(62L),
  ResourceBaseline8Cost(63L),
  AssignmentBaseline9Work(64L),
  AssignmentBaseline9Cost(65L),
  TaskBaseline9Work(66L),
  TaskBaseline9Cost(67L),
  ResourceBaseline9Work(68L),
  ResourceBaseline9Cost(69L),
  AssignmentBaseline10Work(70L),
  AssignmentBaseline10Cost(71L),
  TaskBaseline10Work(72L),
  TaskBaseline10Cost(73L),
  ResourceBaseline10Work(74L),
  ResourceBaseline10Cost(75L),
  PhysicalPercentComplete(76L),
  TaskWork(77L),
  TaskCost(78L),
  ResourceWork(79L),
  ResourceCost(80L),
  AssignmentWork(81L),
  AssignmentCost(82L),
  Undefined(-1L),
  ;
  private long numVal;

  TimephasedDataType(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
